<h1 id="tocheading">Finding Patterns in Data using IBM Power and PowerAI</h1>
<div id="toc"></div>

In this lab we will explore an open source data set, and discover how we can use the tools that are part of **PowerAI** to explore and discover patterns in the data.  For this lab, we will make use of the Lending Club data set, **scikit learn, Tensorflow and Keras**.  Here is a brief description about Lending Club.

```
About the author's
Dustin VanStee - Data Scientist
Bob Chesebrough - Data Scientist
IBM Cognitive Systems Solution Center
contact : vanstee@us.ibm.com
```

*Change Log*
```
010819 DVS : Switched to Anaconda Python environment
```

<img src="https://github.com/dustinvanstee/random-public-files/raw/master/techu-banner.png" width="800" height="500" align="middle"/>

[Lending Club (LC)](https://www.lendingclub.com/) is the world’s largest online marketplace connecting borrowers and investors. It is transforming the banking system to make credit more affordable and investing more rewarding. Lending Club operates at a lower cost than traditional bank lending programs and pass the savings on to borrowers in the form of lower rates and to investors in the form of solid risk-adjusted returns.

**The DATA**  
The original data set is downloaded from [LC](https://www.lendingclub.com/info/download-data.action) covering complete loan data for all loans issued through the 2007-2018, including the current loan status (Current, Late, Fully Paid, etc.) and latest payment information. Additional features include credit history, number of finance inquiries, address including zip codes, and state, and collections among others. It is quite rich and is an excellent example of credit risk data.  Interestingly, Goldman Sachs’ new peer-to-peer lending platform called Marcus was built almost entirely using the Lending Club data.

Here is a link to some extra information regarding the fields of the data set.
[Data Dictionary](https://github.com/dustinvanstee/mldl-101/blob/master/lab5-powerai-lc/LCDataDictionary.csv)

**Important**

In this notebook, we will play with the lending club data, conduct a set of exploratory analysis and try to apply various machine learning techniques to predict borrower’s default. We took a small sample of loans made in 2016 (130K) to help speed up the processing time for the lab


Note : to remove a lot of the busy verbose code, we are making using of a utility python file called lc_utils.py.  For implemenation details you can refer here [python code](https://github.com/dustinvanstee/mldl-101/blob/master/lab5-powerai-lc/lc_utils.py)

### Quick word on the data science method
<img src="https://github.com/dustinvanstee/random-public-files/raw/master/dsx-methodology.png" width="900" height="700" align="middle"/>

Here we will use these simple high level steps to work through a typical data science problem.  This workflow is meant to be a high level guide, but in practice this is a highly iterative approach ...

### Goals

* Perform some initial analysis of the data for **Business Understanding**
* **Prepare the Data** for our visualization and modeling
* **Visualize** the data
* Model using **Dimension Reduction** and **Classification** techniques
* **Evaluate** the approach

## Business/Data Understanding and Preparation
<img src="https://github.com/dustinvanstee/random-public-files/raw/master/techu-bu-dp.png" width="800" height="500" align="middle"/>

### Environment bootstrapping
Run the following commands to install a few python packages for later use

In [1]:
#!pip install -q jupyter-pip
#!pip install -q brunel
import brunel
# !git fetch origin master
# !git reset --hard origin/master

### Import Libraries

In [2]:
# Code functions that are needed to run this lab
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import time
from datetime import datetime
import math

import pandas as pd
#pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

import glob

# custom library for some helper functions 
from sklearn.base import BaseEstimator, TransformerMixin
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

import myenv as myenv
myenv.CLASS_ENVIRONMENT = 'dv-mac'
from lc_utils import *

CLASS_ENVIRONMENT = dv-mac

Using TensorFlow backend.

### Load the Data
Here we load data that was previously downloaded from lendingclub.com.  For speed of this lab, we are restricting the number of loans ~ 130K

In [3]:
loan_df = load_sample_data()
loan_df_orig = loan_df
loan_df.head()

**load_sample_data** : Loading /data/work/osa/2018-04-lendingclub/lending-club-loan-data/lendingclub.com/LoanStats_securev1_2016Q1.csv

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,76003542,NaN,16000.0,16000.0,16000.0,36 months,5.32%,481.84,A,A1,Security specialist,8 years,RENT,105000.0,Not Verified,Mar-2016,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,206xx,MD,15.02,1.0,Nov-2000,720.0,724.0,0.0,9.0,NaN,9.0,0.0,6219.0,27.9%,21.0,w,0.00,0.00,16098.340000,16098.34,16000.00,98.34,0.00,0.0,0.0,May-2016,16107.80,NaN,Nov-2016,679.0,675.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,23525.0,0.0,3.0,2.0,2.0,8.0,17306.0,69.0,0.0,1.0,3770.0,50.0,22300.0,1.0,3.0,1.0,3.0,3361.0,13632.0,29.7,0.0,0.0,124.0,184.0,22.0,8.0,0.0,52.0,NaN,8.0,9.0,0.0,2.0,3.0,2.0,5.0,7.0,6.0,14.0,3.0,9.0,0.0,0.0,0.0,2.0,95.2,0.0,0.0,0.0,47543.0,23525.0,19400.0,25243.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,76023477,NaN,17000.0,17000.0,17000.0,36 months,9.75%,546.55,B,B3,Kindergarten Teacher,< 1 year,MORTGAGE,40000.0,Verified,Mar-2016,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,440xx,NC,24.30,0.0,Aug-2006,705.0,709.0,0.0,NaN,NaN,4.0,0.0,14009.0,85.9%,8.0,w,1856.98,1856.98,16630.580000,16630.58,15143.02,1487.56,0.00,0.0,0.0,Nov-2017,546.55,Dec-2017,Nov-2017,799.0,795.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,31939.0,0.0,1.0,0.0,0.0,25.0,17930.0,64.0,0.0,0.0,4913.0,72.0,16300.0,1.0,0.0,1.0,0.0,7985.0,2291.0,85.9,0.0,0.0,25.0,115.0,35.0,25.0,0.0,35.0,NaN,6.0,NaN,0.0,3.0,3.0,3.0,5.0,1.0,3.0,7.0,3.0,4.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0,0.0,44131.0,31939.0,16300.0,27831.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,75993535,NaN,15000.0,15000.0,15000.0,60 months,15.31%,359.30,C,C5,Branch Manager,10+ years,MORTGAGE,70000.0,Source Verified,Mar-2016,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,home_improvement,Home improvement,750xx,TX,9.99,0.0,Jan-2002,690.0,694.0,0.0,32.0,NaN,6.0,0.0,11630.0,48.5%,22.0,w,0.00,0.00,17155.045652,17155.05,15000.00,2137.08,17.97,0.0,0.0,Apr-2017,13106.47,NaN,Mar-2017,754.0,750.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,27322.0,0.0,1.0,1.0,1.0,12.0,15692.0,72.0,1.0,2.0,5840.0,60.0,24000.0,3.0,0.0,6.0,3.0,4554.0,9808.0,38.7,0.0,0.0,160.0,152.0,9.0,9.0,3.0,9.0,NaN,8.0,NaN,0.0,2.0,4.0,3.0,6.0,7.0,5.0,12.0,4.0,6.0,0.0,0.0,0.0,2.0,95.5,33.3,0.0,0.0,45706.0,27322.0,16000.0,21706.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,73458582,NaN,2425.0,2425.0,2425.0,36 months,15.31%,84.44,C,C5,Teacher,5 years,MORTGAGE,25000.0,Source Verified,Mar-2016,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,296xx,SC,38.50,0.0,Sep-2007,705.0,709.0,0.0,NaN,NaN,7.0,0.0,10604.0,84.8%,15.0,w,0.00,0.00,2653.180000,2653.18,2425.00,228.18,0.00,0.0,0.0,Dec-2016,2062.67,NaN,Nov-2017,714.0,710.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,97019.0,0.0,4.0,0.0,1.0,24.0,15963.0,65.0,0.0,0.0,7288.0,72.0,12500.0,0.0,0.0,0.0,1.0,13860.0,12.0,99.8,0.0,0.0,102.0,97.0,27.0,24.0,2.0,27.0,NaN,NaN,NaN,0.0,1.0,2.0,1.0,3.0,5.0,2.0,8.0,2.0,7.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0,0.0,115022.0,26567.0,7300.0,24550.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,73511090,NaN,29900.0,29900.0,29900.0,36 months,12.99%,1007.31,C,C2,Executive Chef,10+ years,MORTGAGE,68000.0,Verified,Mar-2016,Late (31-120 days),n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,908xx,CA,17.49,0.0,Nov-1991,675.0,679.0,2.0,NaN,80.0,14.0,1.0,13984.0,62.4%,39.0,w,17215.02,17215.02,17081.110000,17081.11,12684.98,4396.13,0.00,0.0,0.0,Sep-2017,1007.31,Dec-2017,Nov-2017,604.0,600.0,1.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,97.0,530234.0,2.0,2.0,1.0,2.0,3.0,10861.0,72.0,3.0,4.0,2917.0,66.0,22400.0,0.0,0.0,5.0,6.0,40787.0,703.0,91.1,0.0,0.0,124.0,292.0,4.0,3.0,2.0,40.0,NaN,0.0,NaN,0.0,3.0,7.0,3.0,14.0,5.0,11.0,32.0,7.0,13.0,0.0,0.0,0.0,4.0,100.0,100.0,1.0,0.0,596136.0,24845.0,7900.0,15000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

### Descriptive Statistics (1D)
Lets look at some 1D and 2D descriptive statistics for this dataset

In this dataset, we have all types of data.  Numerical, Categorical, Ranked data.  This small module will take you through what is typical done to quickly understand the data

In [4]:
# This function provide the number of rows/cols
# Information on the types of data
# and a report of descriptive statistics

quick_overview_1d(loan_df)

**quick_overview_1d** : There are 133889 observations in the dataset.
**quick_overview_1d** : There are 151 variables in the dataset.
**quick_overview_1d** :
Categorical vs Numerical
**quick_overview_1d** : use df.dtypes ...
float64    112
object      39
Name: type, dtype: int64
**quick_overview_1d** :
******************Dataset Descriptive Statistics (numerical columns only) *****************************

 running df.describe() ....

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,annual_inc_joint,dti_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.0,133887.000000,133887.000000,133887.000000,133887.000000,1.338870e+05,133870.000000,133887.000000,133887.000000,133887.000000,133886.000000,69322.000000,23671.000000,133887.000000,133887.000000,1.338870e+05,133887.000000,133887.000000,133887.000000,133887.000000,133887.000000,133887.000000,133887.000000,1.338870e+05,133887.000000,133887.000000,133887.000000,133887.000000,133887.000000,133887.000000,38074.000000,133887.0,2661.000000,2659.000000,133887.000000,133887.000000,1.338870e+05,133825.000000,133826.000000,133826.000000,133826.000000,130186.000000,133826.000000,116008.000000,133826.000000,133826.000000,133826.000000,133820.000000,1.338870e+05,133826.000000,133825.000000,133825.000000,133887.000000,133887.000000,132776.000000,132712.000000,133887.000000,133887.000000,130241.000000,133887.000000,133887.000000,133887.000000,133887.000000,132843.000000,33756.000000,120089.000000,47783.000000,133887.000000,133887.000000,133887.000000,133887.000000,133887.00000,133887.000000,133887.000000,133887.000000,133887.000000,133887.000000,126266.000000,133887.000000,133887.000000,133887.000000,133887.000000,132758.000000,133887.000000,133887.000000,1.338870e+05,1.338870e+05,1.338870e+05,1.338870e+05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,774.0,774.000000,774.0,774.000000,635.000000,774.000000,774.000000,1087.000000,1087.000000,1087.000000
mean,NaN,15589.394041,15589.394041,15581.984023,460.863923,8.046397e+04,19.547033,0.343476,695.750633,699.750827,0.576498,33.807810,66.361413,12.119922,0.238709,1.861627e+04,25.343245,5695.480540,5692.970475,10951.511813,10946.224173,8583.266797,2292.920647,1.102888e+00,74.221479,13.246068,3186.572260,687.161039,676.487710,0.021257,45.218154,1.0,108617.690135,18.603103,0.006969,259.246596,1.472398e+05,1.045373,2.797147,0.747157,1.625215,21.641175,35704.147819,70.741044,1.373769,2.930006,6183.582271,60.654499,3.636171e+04,0.952924,1.544121,2.187215,4.799159,13509.653738,10857.383932,59.762205,0.010120,21.343491,127.552652,188.682553,13.155243,7.799757,1.671402,23.845607,38.836799,6.812589,35.217672,0.518908,3.809533,5.917796,4.955836,8.00537,8.703407,8.561324,14.702585,5.857858,12.062478,0.000966,0.004765,0.090614,2.248732,94.061616,44.558212,0.130476,0.071172,1.838938e+05,5.412411e+04,2.372274e+04,4.563367e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,155.200801,3.0,11.948320,451.392425,12015.551279,174.638320,6451.076624,50.355115,14.431463
std,NaN,8858.198349,8858.198349,8856.454888,261.612887,7.808478e+04,9.966931,0.908581,31.621999,31.622918,0.878987,22.018719,24.304449,5.762491,0.664568,2.624954e+04,12.094971,6494.839472,6492.855894,7697.093301,7694.867521,7022.361202,2038.167708,8.675113e+00,495.392736,88.361777,6137.727578,69.245431,102.785369,0.166138,22.670729,0.0,44956.566800,7.217561,0.087646,2052.138287,1.631493e+05,1.206477,2.977487,0.989870,1.671529,27.215766,42167.837355,23.145793,1.523488,2.629877,6214.568114,19.945103,3.733985e+04,1.499320,2.788347,2.467997,3.316581,15965.387219,15788.073885,28.001224,0.115733,915.297083,52.093790,98.097844,16.838466,8.921457,1.938519,31.760872,23.083136,5.887389,22.703779,1.336043,2.396556,3.571426,3.204925,4.78620,7.494854,4.803455,8.266546,3.441229,5.734718,0.032073,0.072871,0.506937,1.930450,8.753232,36.039386,0.383625,0.464207,1.870034e+05,4.999403e+04,2.332594e+04,4.552498e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,115.423467,0.0,10.164999,340.693887,6644.414291,184.435131,4220.793077,7.788569,7.940075
min,NaN,1000.000000,1000.000000,775.000000,30.120000,0.000000e+00,-1.000000,0.000000,660.000000,664.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000e+00,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.900000e-09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,18072.000000,1.110000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,2.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.500000e+03,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,7.640000,3.0,0.000000,22.920000,627.960000,0.010000,395.320000,20.000000,0.000000
25%,NaN,8400.000000,8400.000000,8400.000000,265.680000,4.950000e+04,12.640000,0.000000,670.000000,674.000000,0.000000,15.000000,51.000000,8.000000,0.000000,6.578000e+03,17.000000,0.000000,0.000000,5512.810957,5508.190000,3779.450000,853.790000,0.000000e+00,0.000000,0.000000,308.730000,659.000000,655.000000,0.000000,27.000000,1.0,77000.000000,13.455000,0.000000,0.000000,3.222850e+04,0.000000,1.000000,0.000000,0.000000,6.000000,9633.250000,58.000000,0.000000,1.000000,2525.000000,48.000000,1.530000e+04,0.000000,0.000000,0.000000,2.000000,3294.000000,1699.000000,38.300000,0.000000,0.000000,102.000000,121.000000,3.000000,3.000000,0.000000,6.000000,19.000000,2.000000,16.000000,0.000000,2.000000,3.000000,3.000000,5.00000,4.000000,5.000000,9.000000,3.000000,8.000000,0.000000,0.000000,0.000000,1.000000,91.100000,10.000000,0.000000,0.000000,5.422000e+04,2.330500e+04,8.600000e+03,1.658500e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,67.732500,3.0,0.000000,187.935000,6711.922500,27.702500,3195.270000,45.000000,10.000000
50%,NaN,14400.000000,14400.000000,14400.000000,398.520000,6.800000e+04,18.760000,0.000000,690.000000,694.000000,0.000000,30.000000,68.000000,11.000000,0.000000,1.227800e+04,24.000000,3667.540000,3664.390000,8964.060000,8959.890000,6293.850000,1657.730000,0.000000e+00,0.000000,0.000000,525.600000,694.000000,690.000000,0.000000,45.000000,1.0,102000.000000,18.360000,0.000000,0.000000,8.620400e+04,1.000000,2.000000,0.000000,1.000000,13.000000,24144.000000,74.000000,1.000000,2.000000,4664.000000,62.000000,2.640000e+04,0.000000,0.000000,2.000000,4.000000,7685.000000,5284.500000,62.400000,0.000000,0.000000,130.000000,171.000000,8.000000,5.000000,1.000000,13.000000,36.000000,5.000000,32.000000,0.000000,3.000000,5.000000,4.000000,7.00000,7.000000,8.000000,13.000000,5.000000,11.000000,0.000000,0.000000,0.000000,2.000000,97.500000,40.000000,0.000000,0.000000,1.212010e+05,4.101600e+04,1.670000e+04,3.462200e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,123.095000,3.0,12.000000,357.510000,10887.405000,118.470000,5518.400000,50.000000,16.000000
75%,NaN,21000.000000,21000.000000,21000.000000,613.910000,9.500800e+04,25.770000,0.000000,710.000000,714.000000,1.000000,49.000000,82.000000,15.000000,0.000000,2.201100e+04,32.000000,9436.190000,9433.905000,14298.288060,14297.140000,11001.585000,3101.280000,0.000000e+00,0.000000,0.000000,1269.730000,729.000000,725.000000,0.000000,64.000000,1.0,131500.000000,23.380000,0.000000,0.000000,2.174845e+05,2.000000,3.000000,1.000000,2.000000,24.000000,46561.750000,87.000000,2.000000,4.000000,8020.000000,75.000000,4.500000e+04,1.000000,2.000000,3.000000,7.000000,18552.000000,13357.250000,84.400000,0.000000,0.000000,153.000000,241.000000,16.000000,10.000000,3.000000,28.000000,58.000000,10.000000,51.000000,0.000000,5.000000,8.000000,6.000000,10.00000,12.000000,11.000000,19.000000,7.000000,15.000000,0.000000,0.000000,0.000000,3.000000,100.000000,75.000000,0.000000,0.000000,2.635540e+05,6.846750e+04,3.100000e+04,6.125800e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,213.737500,3.0,21.000000,606.120000,16366.035000,263.500000,8591.785000,55.000000,18.000000
max,NaN,40000.000000,40000.000000,40000.000000,1536.950000,9.550000e+06,999.000000,22.000000,845.000000,850.000000,5.000000,192.000000,121.000000,74.000000,46.000000,1.023940e+06,176.000000,31761.790000,31761.790000,50928.655879,50928.660000,40000.000000,16228.300000,5.287200e+02,21245.020000,3824.103600,40688.610000,850.000000,845.000000,12.000000,197.000000,1.0,480000.000000,63.660000,3.000000,224107.000000,5.445012e+06,16.000000,48.000000,20.000000,30.000000,446.000000,796104.000000,558.000000,28.000000,44.000000,776843.000000,198.000000,1.184500e+06,28.000000,79.000000,40.000000,46.000000,463698.000000,282091.000000,189.800000,7.000000,112524.000000,534.000000,852.000000,327.000000,283.000000,51.000000,564.000000,188.000000,25.000000,197.000000,38.000000,36.000000,47.000000,46.000000,57.00000,121.000000,72.000000,101.000000,44.000000,74.000000,2.000000,3.000000,22.000000,31.000000,100.000000,100.000000,9.000000,45.000000,9.999999e+06,1.034841e+06,1.105500e+06,1.183946e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,629.990000,3.0,32.000000,1889.970000,32348.480000,1407.860000,22671.000000,90.000000,65.000000

Here we can get a quick assessment of the statistics for each column.  
**Quick Question** can you answer what was the average income for the 133K loan applicants ?

### Descriptive Statistics (2D)
Since we have over 100 numerical variables, creating a 2D correlation plot may be time consuming and difficult to interpret.  Lets look at correlations on a smaller scale for now....

In [ ]:
# Grab only a subset of columns
cols = ["loan_amnt","annual_inc","dti","fico_range_high","open_acc",'funded_amnt', 'total_acc']
quick_overview_2d(loan_df, cols)

**Quick Question** : Can you find a negatively correlated variable to annual_inc in the chart above?  Can you think of a reason for this result ?

### Create Loan Default column.  This is the column we will predict later
The **loan_status** column contains the information of whether or not the loan is in default. 

This column has more than just a 'default or paid' status.  Since our goal is to build a simple default classifier , we need to make a new column based off the **loan_status** column.

Here we will look at all the categorical values in **loan_status**, and create a new column called **default** based off that one.

In [ ]:
# function to create loan status .... 
loan_df = create_loan_default(loan_df)
loan_df.head(3) # scroll to the right, and see the new 'default' column

### Data Preparation - Handle Null Values aka NaNs ...

One part of the data science process thats especially time consuming is working with unclean data.  This lending club data set is a great example of that.  If you look at the dataframe shown above, you will see a number of columns with the indicator **NaN** .  This means 'not a number' and needs to be dealt with prior to any machine learning steps.  You have many options here.  Some options are listed below...

* Fill with a value -> impute mean/median/min/max/other
* drop rows with NaNs
* drop columns with large number of NaNs 
* use data in other columns to derive

All these methods are possible, but its up to the data scientist / domain expert to figure out the best approach.  There is definitely some grey area involved in whats the best approach.

First, lets understand which columns have NaNs...

In [ ]:
# For every column, count the number of NaNs .... 
# code hint : uses df.isna().sum()

columns_with_nans(loan_df)


As you can see, we have some work to do to clean up the NaN values.  Beyond NaN values, we also have to transform columns if they aren't formatted correctly, or maybe we want to transform a column based on custom requirements.  

```
Example : column=employee_length , values=[1,2,3,4,5,6,7,8,9,10+] formatted as a string
          transform into 
          column=employee_length, [0_3yrs,4_6yrs,gt_6yrs] (categorical:strings)
```
          
Luckily, we took care to process and clean this data below using a few functions.  In practice, **this is where data scientists spend a large portion of their time** as this requires detailed domain knowledge to clean the data.  We have made a fair number of assumptions about how to process the data which we won't go into due to time contraints for the lab.

In [ ]:
# The following cleaning of the data makes use of the steps shown below.....

#loan_df1 = drop_sparse_numeric_columns(loan_df)
#loan_df2 = drop_columns(loan_df1)
#loan_df3 = impute_columns(loan_df2)
#loan_df4 = handle_employee_length(loan_df3)
#loan_df5 = handle_revol_util(loan_df4)
#loan_df6 = drop_rows(loan_df5)

loan_df = clean_lendingclub_data(loan_df)

In [ ]:
# Final Sanity check ....
# If we did our job right, there should not be any NaN's left.  
# Use this convenience function to check

# code hint df.isna().sum()

columns_with_nans(loan_df)

### Data Preparation - Handle Time Objects
Sometimes for columns that contain date information, you may want to break them down into individual columns like month, day, day of week etc.  For our use case, we will create a new column called `time_history` that will indicate how long an applicant has been a borrower.  This is an example of **feature engineering**.  Essentially, using business logic to create a new column (feature) that may have predictive value.

In [ ]:
loan_df = create_time_features(loan_df)
loan_df.head(3)

### Convert Categorical Data to One hot encode ###

If you look above at the data frame, we are almost ready to start building models.  However, there is one important step to complete.  Notice we have some columns that are still built out of string data 
```
example column=home_ownership values=[RENT, MORTGAGE, OWN]
```
Machine learning algorithms only process numerical data, so we need to transform these **categorical columns** into **indicator columns**

From the example above, the transform would yield 3 new columns

```
example column=RENT values=[0,1]
        column=MORTGAGE values=[0,1]
        column=OWN values=[0,1]
```

Conveniently pandas has a nice function called **get_dummies** that we will use for this purpose

In [ ]:
# Transform categorical data into binary indicator columns
# code hint, uses pd.get_dummies

loan_df = one_hot_encode_keep_cols(loan_df)
loan_df.head() # once complete, see how many new columns you have!

### Final Result after data preparation ....

Ok, so you made it here, lets take a look at the final results of your data preparation work.  It may be helpful to  **qualitatively compare** your original data frame to this one and see how different they look..  Execute the cells below to get a sense of what the tranformations accomplished.

In [ ]:
loan_df_orig.head(3)

In [ ]:
loan_df.head(3)

### Data Visualization
As you saw, when you 'describe' a data frame, you get a table statistics showing you the mean,min,max and other statistics about each column.  This is good, but sometimes its also good to look at the histograms of the data as well.  Lets Visualize some of the distributions from our dataset

<img src="https://github.com/dustinvanstee/random-public-files/raw/master/data-visualization.png" width="800" height="500" align="middle"/>

In [ ]:
# Here we plot distribution charts for all the numerical columns in our dataframe
plot_histograms(loan_df)

## Brunel Visualization Examples
### The Growth of Lending Club
Here we use the builtin Brunel Visualization graphics package.  This documentation was useful in the preparation of the following graphs.
* https://brunel.mybluemix.net/docs/Brunel%20Documentation.pdf

In [ ]:
# Build a statistics data frame based on issue date
# aggregate on loan amount
vis_df = loan_df_orig.copy()
vis_df['default'] = loan_df['default']

### Outcome Variable: Loan Status
On the left is the breakdown of all loan status classifications.  On the right is our simple default classification based on our data prep

In [ ]:
a=vis_df.sample(5000) # downsample for speed
%brunel data('a') bar x(loan_status) y(#count:linear) color(loan_status)  percent(#count:overall) tooltip(#all) | stack polar bar y(#count) color(default) percent(#count) tooltip(#all) :: width=1200, height=350

### Borrowing by State 
Most of the money in terms of absolute borrowing is borrowed by people from California. For average loan amount per state, Alaska ranks on top.

In [ ]:
state_stats = pd.concat([vis_df.groupby('addr_state').sum()['loan_amnt'].to_frame().rename(columns = {'loan_amnt':'state_total'}), vis_df.groupby('addr_state').mean()['loan_amnt'].to_frame().rename(columns = {'loan_amnt':'state_mean'})], axis=1)
%brunel data('state_stats') map color(state_total:[blues, reds]) key(ADDR_STATE) label(ADDR_STATE) tooltip(#all) title("Total Loan Amount by State") style('.header {label-location:left}')| map color(state_mean:[blues, reds]) key(ADDR_STATE) label(ADDR_STATE) tooltip(#all) title("Average Loan Amount by State") style('.header {label-location:left}') :: width=1200, height=350

### Loan Purpose
Lets try to get a sense of why people are borrowing ...

In [ ]:
purpose_count = vis_df.groupby('purpose')['loan_status'].count().to_frame().rename(columns = {'loan_status':'count'})
%brunel bubble data('purpose_count') color(COUNT:[blues, reds]) size(COUNT) label(PURPOSE) tooltip(#all)

As you can see, this could go on forever, but hopefully you get a sense of the power of data visualization

### Modelling Phase

<img src="https://github.com/dustinvanstee/random-public-files/raw/master/modeling.png" width="800" height="500" align="middle"/>

### Train / Test set creation

One of the key points in any machine learning workflow is the **partitioning** of the data set into **train** and **test** sets.  The key idea here is that a model is built using the training data, and evaluated using the test data.  

There are more nuances to how you partition data into train/test sets, but for purposes of this lab we will omit these finer points.

In [ ]:
%load_ext autoreload
%autoreload 2
from lc_utils import *

In [ ]:
# Instantiate lendingclub_ml object that will hold our test, and contain methods used for testing.
# Implementation done like this to ease the burden on users for keeping track of train/test sets for different
# models we are going to build.

my_analysis = lendingclub_ml(loan_df)

In [ ]:
# Create a train / test split of your data set.  Paramter is test set size percentage 
# Returns data in the form of dataframes

my_analysis.create_train_test(test_size=0.4)

### Dimension Reduction
For this modeling exercise we will perform a couple of tasks, **dimension reduction** and **classification** as shown in the following diagram.

<img src="https://github.com/dustinvanstee/random-public-files/raw/master/techu-modeling-workflow.png" width="800" height="500" align="middle"/>

**Dimension Reduction** is useful in scenarios when you have a large number of columns and you would like to reduce that down to a compressed representation .  In this lab we will try 2 methods of dimension reduction.  It will be your choice to decide which method you want to use for the classification part of the lab ! (you could even decice to bypass this if you want ...)

## Dimension Reduction - PCA

<img src="https://github.com/dustinvanstee/random-public-files/raw/master/techu-pca.png"  width="200" height="125" align="middle"/>

Principal component analysis (PCA) is a statistical procedure that uses an orthogonal transformation to convert a set of observations of possibly correlated variables into a set of values of linearly uncorrelated variables called principal components. The number of principal components is less than or equal to the number of original variables.

A simple way to think about PCA is that it helps compress the data in a lossy representation of the original dataset.

This will also be used to help us visualize the data as you will see below

In [ ]:
# Dimension Reduction using PCA
my_analysis.build_pca_model(n_components=20)

In the chart above, you can see that we get ok results from PCA.  Using the first 20 principal components, we can account for ~50% of the variance described in the dataset.  **Feel free to change the number of principal components above to see if adding more helps with explained variance.**

## Dimension Reduction - AutoEncoder

<img src="https://github.com/dustinvanstee/random-public-files/raw/master/techu-ae.png"  width="600" height="375" align="middle"/>

An autoencoder is another method that can be used for dimension reduction.  An autoencoder is a **neural network** that tries to reproduce itself given the constraint that it will lose information in the bottleneck layer.  Based on this, its again a lossy representation.  One key difference between autoencoders and PCA is that an autoencoder can find non linear relationships between variables that PCA could not detect.

In [ ]:
# This will build and run your auto-encoder 
# feel free to adjust 
# ae_layers -> needs to be an odd number of layers, and symmetric 
# Regularization -> controls overfitting
# epochs -> number of times to loop thru training set

my_analysis.build_ae_model(ae_layers=[100,25,6,25,100], regularization=0.001, epochs=1)

**Class Contest**  lets see who can find the best settings for the neural network to minimize loss!  Just yell out your results and instructor will add to the leaderboard!

# Now update our test dataframe with new columns that are predicted by our PCA and Autoencoder models.  

Here we will now take the models that we built and pass our test data set through the models.   By doing this, we will have reduced the number features in our data set by a significant amount (~177 colums => ~5-20 columns!)  .  

In this step we will add new columns to our test/train data frames for both our PCA model and our autoencoder model.  Don't worry about the details of this step, its just required for some followon visualization, and training steps ahead.

In [ ]:
my_analysis.update_train_test_df()

### Cool Visualizations using our dimension reduction columns

Next we will plot a few scatterplot grids based on our pricipal component and autoencoder representations of the data

We will color each data point using this key
```
Green -> Fully paid or current loan
Red   -> Loan in default
```

In [ ]:
# This will take a minute or so ...
my_analysis.visualize_dimred_results(mode='pca')

In [ ]:
# This will take a minute or so ...
my_analysis.visualize_dimred_results(mode='ae')

If you can discern a pattern between the red / green dots, its likely we can use a classifier to automatically seperate them! We'll see that in a few more sections

### Heatmap commentary
Using a heatmap can be another good visualization tool.  You can use this to get a sense of how the data correlates to each other.  In the code below, play with the **sortColumn** input .  In the example below we are sorting by principal component 0, which has the most information encoded in that column.  See if you can find out what PC0 might be composed of.  Try it for PC1, or AE0, AE1...

Pro tip, to get the most out of a heatmap, all the data needs to be normalized on a common 0 -> 1 scale so that the coloring of the columns works out ..

In [ ]:
# This will take a minute or so ...
bob_heatmap_lc(my_analysis.test_df,sortColumn='PC0',add_corr=1)

The resolution is quite small, but try to find columns that go from solid red on bottom to black on top. That would be an indication of high correclation to your sort column

# Final Step - Lending Club Default Prediction

<img src="https://github.com/dustinvanstee/random-public-files/raw/master/techu-modeling-traintest.png"  width="600" height="375" align="middle"/>

Here we will build a classifier to predict if loan will fail or not.  We will us a 
** Deep Learning Classifier **  .  You will have 3 options for data sources, 
* the raw data
* PCA dimension reduction features
* Autoencoder features

To evaluate our model, we will use a simple contingency table (showing true/false positve/negative).  However, this is a fairly simplistic method.  Better method that data scientists use are F1 score, and PR/ROC curves but thats beyond the scope of this lab.

Step 1 here is to set our baseline result.  In this example, we are dealing with a **skewed** dataset.  This means, on average, most people will not default, and they pay their loan off.  If you built a classifier that just predicted no default, you would be right most of the time.  Lets see the stats from our dataset below....

In [ ]:
# Set our baseline
my_analysis.train_df['default'].describe()

As you can see, **only ~12.8% of the applicants default**.  Any classifier we build must be better than this, or we aren't doing a very good job ;)

In [ ]:
# modes
# pca           : principal components only
# ae            : autoencoder components only
# raw           : all the data non reduced
# raw_no_grades : all the data non reduced except the grade info provided by lending club

mode = 'pca' # ae , raw, raw_no_grades

if(mode == 'pca') :
            x_cols = [x for x in my_analysis.train_df.columns if 'PC' in x]
elif(mode == 'ae') :
            x_cols = [x for x in my_analysis.train_df.columns if 'AE' in x]
elif(mode == 'raw') :
            x_cols = [x for x in my_analysis.train_df.columns if 'AE' not in x and 'PC' not in x]
elif(mode == 'raw_no_grades') :
            x_cols = [x for x in my_analysis.train_df.columns if 'AE' not in x and 'PC' not in x]
            import re
            x_cols = [x for x in x_cols if not re.match('^[ABCDEFG]',x)]

#print(x_cols)
my_analysis.build_evaluate_dl_classifier(x_cols, epochs=25,batch_size=32,regularization=0.001)

**Class Contest** See who can get the best accuracy, shout out your answers to the instructor and see if you can top the leaderboard
* accuracy = (true positive + true negative) / total

### Credits 
* Bob Chesebrough - IBM CSSC Data Scientist
* Catherine Cao - IBM FSS Data Scientist
* [Hands on Machine Learning - Geron] (https://www.oreilly.com/library/view/hands-on-machine-learning/9781491962282/)

### More Learning
* Coursera Deeplearning.ai  (Ng)
* Coursera Machine Learning (Ng)